/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MathTopic = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'color' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LessonExample = IDL.Record({
  'id' : IDL.Text,
  'solution' : IDL.Text,
  'problem' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'explanation' : IDL.Text,
  'examples' : IDL.Vec(LessonExample),
  'topicId' : IDL.Text,
});
export const PracticeQuestion = IDL.Record({
  'id' : IDL.Text,
  'correctOption' : IDL.Nat,
  'question' : IDL.Text,
  'explanation' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'topicId' : IDL.Text,
});
export const QuizResult = IDL.Record({
  'total' : IDL.Nat,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'topicId' : IDL.Text,
});
export const UserProgress = IDL.Record({
  'questionsAnswered' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'quizHistory' : IDL.Vec(QuizResult),
  'startedTopics' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllTopics' : IDL.Func([], [IDL.Vec(MathTopic)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLessonsForTopic' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getPracticeQuestionsForTopic' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PracticeQuestion)],
      ['query'],
    ),
  'getQuizQuestions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PracticeQuestion)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTopicStarted' : IDL.Func([IDL.Text], [], []),
  'recordQuizResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedBackend' : IDL.Func([], [], []),
  'submitAnswer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MathTopic = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'color' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LessonExample = IDL.Record({
    'id' : IDL.Text,
    'solution' : IDL.Text,
    'problem' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'explanation' : IDL.Text,
    'examples' : IDL.Vec(LessonExample),
    'topicId' : IDL.Text,
  });
  const PracticeQuestion = IDL.Record({
    'id' : IDL.Text,
    'correctOption' : IDL.Nat,
    'question' : IDL.Text,
    'explanation' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'topicId' : IDL.Text,
  });
  const QuizResult = IDL.Record({
    'total' : IDL.Nat,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'topicId' : IDL.Text,
  });
  const UserProgress = IDL.Record({
    'questionsAnswered' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'quizHistory' : IDL.Vec(QuizResult),
    'startedTopics' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllTopics' : IDL.Func([], [IDL.Vec(MathTopic)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLessonsForTopic' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getPracticeQuestionsForTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PracticeQuestion)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PracticeQuestion)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTopicStarted' : IDL.Func([IDL.Text], [], []),
    'recordQuizResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedBackend' : IDL.Func([], [], []),
    'submitAnswer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };