/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lesson {
  'id' : string,
  'title' : string,
  'explanation' : string,
  'examples' : Array<LessonExample>,
  'topicId' : string,
}
export interface LessonExample {
  'id' : string,
  'solution' : string,
  'problem' : string,
}
export interface MathTopic {
  'id' : string,
  'title' : string,
  'icon' : string,
  'color' : string,
  'description' : string,
}
export interface PracticeQuestion {
  'id' : string,
  'correctOption' : bigint,
  'question' : string,
  'explanation' : string,
  'options' : Array<string>,
  'topicId' : string,
}
export interface QuizResult {
  'total' : bigint,
  'score' : bigint,
  'timestamp' : bigint,
  'topicId' : string,
}
export interface UserProfile { 'name' : string }
export interface UserProgress {
  'questionsAnswered' : bigint,
  'correctAnswers' : bigint,
  'quizHistory' : Array<QuizResult>,
  'startedTopics' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllTopics' : ActorMethod<[], Array<MathTopic>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLessonsForTopic' : ActorMethod<[string], Array<Lesson>>,
  'getPracticeQuestionsForTopic' : ActorMethod<
    [string],
    Array<PracticeQuestion>
  >,
  'getQuizQuestions' : ActorMethod<[string], Array<PracticeQuestion>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[Principal], UserProgress>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTopicStarted' : ActorMethod<[string], undefined>,
  'recordQuizResult' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedBackend' : ActorMethod<[], undefined>,
  'submitAnswer' : ActorMethod<[string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];